# Generated by Django 5.2.7 on 2025-11-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skuter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nomi')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modeli')),
                ('narx_soat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='kunlik narx (UZS)')),
                ('mavjud', models.BooleanField(default=True, verbose_name='Mavjud')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='skuter_rasmlari/', verbose_name='Rasm')),
                ('tavsif', models.TextField(blank=True, verbose_name='Tavsif')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
